package com.example.project.sql_db;

public class Samples {
    public static final Question[] questions = {
            new Question(1, "The Nintendo company was founded in 1889 and originally made what?",
                    "Wooden cats","Playing cards","Fancy shoes","Plumber action figures",2,"n"),
            new Question(2, "What was the sequel to Super Mario World called?",
                    "Super Mario World 2: Plumbing Adventures","Super Mario World 2: Wario War","Super Mario World 2: Yoshi's Island","Super Mario World 2: Pipe Dreams",3,"n"),
            new Question(3, "How many Legend of Zelda games are there?",
                    "19","10","5","12",4,"n"),
            new Question(4, "There's an urban myth that suggests that Donkey Kong was supposed to be called something else. What was the title?",
                    "Monkey Mario Mayhem","Monkey Kong","Simian Plumbing","King King",4,"n"),
            new Question(5, "In which year was the game Duck Hunt released?",
                    "1995","1999","1984","2002",3,"n"),
            new Question(6, "Which country does the character Kirby come from?",
                    "Japan","Marshmallow Island","Dreamland","Sweden",1,"n"),
            new Question(7, "How many different games has Mario appeared in?",
                    "45","Over 100","152","Over 200",4,"n"),
            new Question(8, "In Animal Crossing: Happy Home Designer, who is Digby's twin sister?",
                    "Princess Peach","Isabelle","Princess Daisy","Sharon",2,"n"),
            new Question(9, "What year did the Nintendo Switch first come out?",
                    "2010","2012","2017","2020",3,"n"),
            new Question(10, "What is Mario's home stage in Super Smash Bros?",
                    "Kew Gardens","Congo Jungle","Peach's Castle Mushroom Kingdom","Hyrule Castle",3,"n"),

            new Question(11, "How many Playstation consoles are there right now?",
                    "2","3","4","12",3,"p"),
            new Question(12, "How many Playstation games are there IN TOTAL?",
                    "Over 4600","2874","Over 6000","Under3264",1,"p"),
            new Question(13, "Which Playstation console generation has sold the most units?",
                    "2","3","4","1",1,"p"),
            new Question(14, "Playstations were invented in which country?",
                    "China","Britain","Korea","Japan",4,"p"),
            new Question(15, "Which of these buttons is NOT on a Playstation controller?",
                    "R2","L1","Y","Left",3,"p"),
            new Question(16, "Mario was originally a Playstation game character. True or false?",
                    "True","False","","",2,"p"),
            new Question(17, "The US Air Force once stuck 1,760 Playstations together to make a supercomputer. True or false?",
                    "True","False","","",1,"p"),
            new Question(18, "What else can you use Playstations for apart from gaming?",
                    "saving the dolphins","Playing DVDs and CDs","Doing the washing up","As a dance partner",2,"p"),
            new Question(19, "Who is the character that is furry, has pants, has a big snout and spins like a top to attack?",
                    "Spyro","Ratchet","Zelda","Crash Bandicoot",4,"p"),
            new Question(20, "Here's a tricky one. What colour was the underside of the discs on the Playstation 1?",
                    "White","Pink","Purple","Black",4,"p"),

            new Question(21, "Which wrestler helped launch the Xbox at a special event in 2001?",
            "John Cena","The Rock","The Undertaker","Triple H",2,"x"),
            new Question(22, "What was the console originally going to be called?",
                    "Game Port","Gamestation","11-X","Noah's Arcade",3,"x"),
            new Question(23, "What was the last original game to be released for the Xbox in North America?",
                    "LEGO Batman:The Videogame","Rock Band 2","Sonic Unleashed","Madden 09",4,"x"),
            new Question(24, "In which year was the Xbox 360 released?",
                    "2005","2006","2007","2010",1,"x"),
            new Question(25, "When the Xbox 360 had a malfunction, what colour did the light around the on switch change to?",
                    "BLue","Red","Green","Orange",2,"x"),
            new Question(26, "What was the name of the Xbox camera accessory?",
                    "iToy","Kinect","BoxCam","The Eye of Gates",2,"x"),
            new Question(27, "What is the biggest selling game for Xbox One?",
                    "Star Wars Battlefront","Minecraft","Grand Theft Auto V","FIFA 17",3,"x"),
            new Question(28, "What colors was the original Xbox",
                    "Black with white","Green with white","White with black","Black with green",4,"x"),
            new Question(29, "What Xbox game puts you in charge of defending a garden",
                    "Zombie Gardener","Plants vs. Zombies","Green Fingers","Zombie Agriculture",2,"x"),
            new Question(30, "When will the Xbox Series X console be released?",
                    "June 1","May","Late 2020","2021",3,"x"),

    };
}
